#!/bin/bash

ECHO ""

if [ ! -d "env" ]
then
    ECHO 'making env'

    virtualenv --python=python3 env

    . env/bin/activate

    ECHO 'installing requirements'
    pip install -r requirements.txt
else
    ECHO "##### a directory named 'env' already exists ####"
fi

ECHO ""

if [ ! -d "instance" ]
then
    ECHO 'create instance directory'
    mkdir instance
    touch instance/__init__.py
    cp default_site_settings.confg instance/site_settings.py
else
    ECHO "###### a directory named 'instance' already exists #####"
fi

ECHO ""

ECHO "Don't forget to update site_settings and use create the initial database from migrations file."


